services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./fe:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
      NGINX_HOST: ${NGINX_HOST}
    depends_on:
      - be
      - db

  be:
    build: ./be
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
